"use client";

import React from 'react';
import Link from 'next/link';
import './contact.css';

export default function ContactPageClient() {
  return (
    <div className="contact-page-wrapper">
      
<section className="hero">
<div className="container hero-grid">
<div>
<div className="breadcrumb">Home <b>›</b> <span>Contact Us</span></div>
<div className="eyebrow">Start a Conversation</div>
<h1 style={{ marginTop: '13px' }}>Tell us what you need to <em>survey, map or build.</em></h1>
<p className="lead">Share your project location, source data, expected deliverables, accuracy requirement and timeline. Our team will review the requirement and recommend a practical GIS, drone survey or development workflow.</p>
<div className="hero-actions"><a className="btn btn-primary" href="#project-form">Share Your Requirement →</a><a className="btn btn-secondary" href="mailto:info@techmapperz.com">Email Project Scope</a></div>
<div className="hero-points"><div><i></i><span>GIS, CAD, raster and point-cloud projects</span></div><div><i></i><span>Drone survey and mapping requirements</span></div><div><i></i><span>Web and Mobile GIS applications</span></div><div><i></i><span>India and international project support</span></div></div>
</div>
<div className="contact-window">
<div className="map-card"><div className="window-top"><span>TECHMAPPERZ · PROJECT CONTACT MAP</span><div className="dots"><i></i><i></i><i></i></div></div>
<div className="map-stage">
<svg viewBox="0 0 620 470" preserveAspectRatio="none"><rect width="620" height="470" fill="#dbeaf2"/><g fill="#eef6f8" stroke="#a6c7d8" strokeWidth="2"><path d="M80 40 L215 18 L287 72 L361 54 L447 111 L527 97 L598 170 L567 260 L610 334 L533 441 L417 419 L350 456 L254 405 L167 431 L99 365 L36 281 L63 194 L21 123 Z"/><path d="M213 105 L303 73 L358 112 L343 173 L278 202 L222 164 Z"/><path d="M372 211 L465 167 L529 208 L505 288 L427 316 L369 274 Z"/><path d="M156 248 L241 213 L296 274 L265 348 L177 366 L115 311 Z"/></g><g fill="none" stroke="#87b0c7" opacity=".68"><path d="M40 335 C132 251 201 355 302 258 S465 161 598 218" strokeWidth="18"/><path d="M40 335 C132 251 201 355 302 258 S465 161 598 218" stroke="#f7fbfd" strokeWidth="7"/><path d="M82 80 L545 405" strokeWidth="2" strokeDasharray="7 8"/><path d="M38 203 L580 102" strokeWidth="2" strokeDasharray="7 8"/></g><g fill="#1267b1"><circle cx="376" cy="242" r="7"/><circle cx="459" cy="189" r="7"/></g><g fill="#e33434"><circle cx="427" cy="257" r="9"/><circle cx="325" cy="293" r="9"/></g><g fill="none" stroke="#1267b1" strokeWidth="2"><circle cx="427" cy="257" r="17" opacity=".3"/><circle cx="325" cy="293" r="17" opacity=".3"/></g></svg>
<div className="map-panel"><strong>Project enquiry inputs</strong><span>Location · Area · Data · Accuracy · Deliverables · Timeline</span></div>
<div className="office-float office-delhi"><b><span className="pulse"></span>Delhi operations</b><span>Client coordination & service support</span></div>
<div className="office-float office-kolkata"><b><span className="pulse"></span>Kolkata delivery</b><span>GIS production & development team</span></div>
</div></div></div>
</div></section>
<div className="quick-strip"><div className="container quick-grid"><div className="quick-card"><small>Email</small><b>info@techmapperz.com</b><span>Project scopes and general enquiries</span></div><div className="quick-card"><small>Call</small><b>+91 96430 02065</b><span>Delhi and business enquiries</span></div><div className="quick-card"><small>Call</small><b>+91 33 3575 2689</b><span>Kolkata office and delivery support</span></div><div className="quick-card"><small>Project coverage</small><b>India & overseas</b><span>Remote production and field-partner models</span></div></div></div>
<section className="enquiry" id="project-form"><div className="container enquiry-grid">
<div className="form-info"><div className="eyebrow">Project Requirement Form</div><h2>Better inputs lead to a more accurate proposal.</h2><p>A brief description is enough to start. The details below help us assess methodology, team size, timeline, accuracy and commercial assumptions.</p>
<div className="send-list"><div className="send-item"><span className="send-no">01</span><div><b>Project geography</b><p>Location, area in sq. km/hectares or corridor length and width.</p></div></div><div className="send-item"><span className="send-no">02</span><div><b>Available inputs</b><p>Drone images, LiDAR/LAS, satellite imagery, CAD, GCP/DGPS, specifications or samples.</p></div></div><div className="send-item"><span className="send-no">03</span><div><b>Expected deliverables</b><p>GIS database, DWG, orthomosaic, DTM/DSM, contours, reports, dashboard or mobile app.</p></div></div><div className="send-item"><span className="send-no">04</span><div><b>Acceptance criteria</b><p>Required accuracy, coordinate system, coding schema, QA checklist and delivery schedule.</p></div></div></div>
<div className="secure-note"><strong>Confidential or large files?</strong> Submit only a project summary here. Ask us for a secure upload location before transferring imagery, LiDAR, drawings or client-confidential datasets. <a href="mailto:info@techmapperz.com">Request a secure transfer link →</a></div></div>
<form className="form-card" id="contactForm"><div className="form-head"><div><h3>Discuss your project</h3><p>Fields marked with * are required. This prototype does not send data to a server.</p></div><span className="form-badge">Project-focused enquiry</span></div>
<div className="form-grid"><div className="field"><label>Full name <span>*</span></label><input required placeholder="Your name" /></div><div className="field"><label>Organisation <span>*</span></label><input required placeholder="Company / department" /></div><div className="field"><label>Work email <span>*</span></label><input required type="email" placeholder="name@company.com" /></div><div className="field"><label>Phone / WhatsApp</label><input placeholder="Country code and number" /></div><div className="field"><label>Country <span>*</span></label><select required><option value="">Select country</option><option>India</option><option>Spain</option><option>United Kingdom</option><option>United States</option><option>United Arab Emirates</option><option>Other</option></select></div><div className="field"><label>Required service <span>*</span></label><select required><option value="">Select service</option><option>GIS Mapping & Digitisation</option><option>Drone Photogrammetry Survey</option><option>Drone LiDAR Survey</option><option>LiDAR / Point-Cloud Processing</option><option>Topographic & Contour Mapping</option><option>Feature Extraction</option><option>Utility / Pipeline Mapping</option><option>Web or Mobile GIS Development</option><option>Website Development</option><option>Mobile App Development</option><option>Other</option></select></div><div className="field"><label>Industry</label><select><option value="">Select industry</option><option>Infrastructure & AEC</option><option>Government & Land Administration</option><option>Utilities & Energy</option><option>Mining & Natural Resources</option><option>Agriculture & Environment</option><option>Transportation</option><option>Telecommunications</option><option>Other</option></select></div><div className="field"><label>Project location</label><input placeholder="City, state, country or corridor" /></div><div className="field"><label>Approximate project size</label><input placeholder="e.g. 75 sq. km or 120 km corridor" /></div><div className="field"><label>Required timeline</label><select><option value="">Select expected timeline</option><option>Urgent / under 2 weeks</option><option>2–4 weeks</option><option>1–3 months</option><option>3–6 months</option><option>Long-term / annual programme</option><option>To be discussed</option></select></div><div className="field full"><label>Available data and required deliverables</label><textarea placeholder="Mention source files, coordinate system, expected formats, accuracy, feature codes, quantity, sample data and QA requirements."></textarea></div><div className="field full"><label>Attach a small scope document or sample</label><div className="file-box">Recommended: PDF, DOCX, XLSX, JPG or a small sample archive. Do not upload sensitive or very large project data through a public form.<input type="file" /></div></div></div>
<label className="check"><input required type="checkbox" /><span>I agree that Techmapperz may use these details to respond to this enquiry. No project data should be submitted without the necessary client permission.</span></label><button className="btn btn-primary btn-wide" type="submit">Submit Project Requirement →</button><div className="success" id="successMessage">Thank you. In the live website, this message will confirm submission and trigger an email or CRM notification.</div></form>
</div></section>
<section><div className="container"><div className="section-head"><div className="copy"><div className="eyebrow">What Happens Next</div><h2 style={{ marginTop: '12px' }}>A clear path from enquiry to proposal.</h2><p>The contact page should set realistic expectations and help qualified buyers understand the next steps.</p></div><div className="side-note">Avoid promising an instant price before the area, input quality, accuracy and output specification are understood.</div></div><div className="process-grid"><article className="process-card"><b>01</b><h3>Requirement review</h3><p>We examine the scope, location, available data, deliverables, schedule and known constraints.</p></article><article className="process-card"><b>02</b><h3>Technical clarification</h3><p>Our team confirms accuracy, survey controls, coding schema, file formats and acceptance criteria.</p></article><article className="process-card"><b>03</b><h3>Method and estimate</h3><p>We prepare an execution approach, assumptions, resource plan, timeline and commercial proposal.</p></article><article className="process-card"><b>04</b><h3>Project mobilisation</h3><p>After agreement, project communication, inputs, milestones, QA/QC and review workflow are established.</p></article></div></div></section>
<section className="contact-options"><div className="container"><div className="section-head"><div className="copy"><div className="eyebrow" style={{ color: '#91d7ff' }}>Choose the Right Contact</div><h2 style={{ marginTop: '12px' }}>Not every conversation needs the full project form.</h2><p>Use the most relevant contact path so that your request reaches the correct team.</p></div></div><div className="option-grid"><article className="option-card"><span className="option-icon">01</span><h3>Project enquiries</h3><p>GIS, drone, LiDAR, Web GIS, website and mobile application requirements.</p><a href="#project-form">Share requirement →</a></article><article className="option-card"><span className="option-icon">02</span><h3>Partnerships</h3><p>Survey partnerships, subcontracting, consortium bids and international production support.</p><a href="mailto:info@techmapperz.com?subject=Partnership%20Enquiry">Discuss partnership →</a></article><article className="option-card"><span className="option-icon">03</span><h3>Careers</h3><p>GIS production, drone operations, software development, design and business-development opportunities.</p><a href="mailto:info@techmapperz.com?subject=Career%20Enquiry">Send career enquiry →</a></article><article className="option-card"><span className="option-icon">04</span><h3>Project support</h3><p>Existing clients can share a project reference, delivery issue or approved revision request.</p><a href="mailto:info@techmapperz.com?subject=Existing%20Project%20Support">Contact support →</a></article></div></div></section>
<section><div className="container"><div className="section-head"><div className="copy"><div className="eyebrow">Our Offices</div><h2 style={{ marginTop: '12px' }}>Delivery from Kolkata. Client support across India and overseas.</h2><p>Use office information for meetings and correspondence. Confirm an appointment before visiting.</p></div></div><div className="offices-grid"><div className="office-cards"><article className="office-card"><small>Production & registered operations</small><h3>Kolkata</h3><p>CF 401, Block CF, Sector 1, Salt Lake, Kolkata, West Bengal, India.</p><span className="contact-line"><b>Phone:</b> +91 33 3575 2689</span><span className="contact-line"><b>Email:</b> info@techmapperz.com</span><a className="btn btn-secondary" style={{ marginTop: '18px' }} href="mailto:info@techmapperz.com?subject=Kolkata%20Office%20Meeting">Request a meeting</a></article><article className="office-card"><small>Service & client coordination</small><h3>New Delhi</h3><p>55, Lane 2, Westend Marg, Saidullajab, near Saket Metro Station, New Delhi, India.</p><span className="contact-line"><b>Phone:</b> +91 96430 02065</span><span className="contact-line"><b>Email:</b> info@techmapperz.com</span><a className="btn btn-secondary" style={{ marginTop: '18px' }} href="mailto:info@techmapperz.com?subject=Delhi%20Office%20Meeting">Request a meeting</a></article></div><div className="office-map"><svg viewBox="0 0 620 390" preserveAspectRatio="none"><rect width="620" height="390" fill="#dceaf2"/><g fill="#f4f9fb" stroke="#a8c5d6" strokeWidth="2"><path d="M31 87 L154 31 L291 45 L383 25 L504 71 L585 142 L572 242 L609 323 L510 371 L404 348 L319 379 L223 343 L121 360 L50 296 L66 205 Z"/></g><g fill="none" stroke="#8cb4c9"><path d="M40 313 C148 226 234 324 332 217 S495 126 599 191" strokeWidth="20"/><path d="M40 313 C148 226 234 324 332 217 S495 126 599 191" stroke="#fff" strokeWidth="8"/><path d="M82 78 L540 335" strokeWidth="2" strokeDasharray="8 8"/></g><g fill="#e33434"><circle cx="255" cy="244" r="9"/><circle cx="407" cy="202" r="9"/></g><g fill="none" stroke="#e33434" strokeWidth="2"><circle cx="255" cy="244" r="20" opacity=".28"/><circle cx="407" cy="202" r="20" opacity=".28"/></g><text x="220" y="279" fill="#0b2341" fontSize="15" fontWeight="800">Kolkata</text><text x="419" y="190" fill="#0b2341" fontSize="15" fontWeight="800">New Delhi</text></svg><div className="legend"><b>Techmapperz offices</b>Meeting by prior appointment · Project delivery can be remote or field-based.</div></div></div></div></section>
<section className="faq"><div className="container"><div className="section-head"><div className="copy"><div className="eyebrow">Contact FAQs</div><h2 style={{ marginTop: '12px' }}>Useful details before you submit an enquiry.</h2></div></div><div className="faq-grid"><details open><summary>What information is required for a GIS or drone quotation?</summary><p>Share the location, area or corridor length, source data, expected outputs, accuracy, coordinate system, timeline and sample specifications. These determine the methodology and effort.</p></details><details><summary>Can we send raw drone images or LiDAR data?</summary><p>Yes. First send a summary and small representative sample. Large or confidential datasets should be transferred only through an approved secure link.</p></details><details><summary>Do you work outside Kolkata and Delhi?</summary><p>Yes. GIS production and application-development work can be delivered remotely. Field survey coverage depends on project location, permissions, mobilisation and local operating conditions.</p></details><details><summary>Can Techmapperz join a consortium or work as a subcontractor?</summary><p>Yes, subject to technical fit, commercial terms, role clarity, client permissions and data-confidentiality requirements.</p></details><details><summary>How quickly will we receive a proposal?</summary><p>The timeline depends on scope clarity. A small, well-defined production assignment can be assessed faster than a survey project requiring permissions, site mobilisation, control planning or partner coordination.</p></details><details><summary>Can you sign an NDA before reviewing data?</summary><p>Commercially reasonable confidentiality arrangements can be discussed before receiving sensitive project information.</p></details></div></div></section>
<section className="final-cta"><div className="container"><div className="cta-box"><div><h2>Have a scope of work ready?</h2><p>Email the document with the project location, area, inputs, required accuracy, deliverables and delivery schedule. We will use it to prepare the next technical discussion.</p></div><div className="cta-actions"><a href="mailto:info@techmapperz.com?subject=New%20GIS%20or%20Drone%20Project%20Scope" className="btn btn-primary">Email Your Scope</a><a href="#project-form" className="btn btn-secondary">Complete the Form</a></div></div></div></section>

    </div>
  );
}
